---
version: "2.1"
services:
  omada-controller:
    image: lscr.io/linuxserver-labs/omada-controller:latest
    container_name: omada-controller
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/data:/config
    ports:
      - 8088:8088
      - 8043:8043
      - 29810:29810
      - 29811:29811
      - 29812:29812
      - 29813:29813
      - 29814:29814
    restart: unless-stopped